### PR TITLE
Move some logic into a module

### PR DESCRIPTION
**Pull request by jenskutilek**
I run into an issue with the DOCUMENTEXPORTED callbacks. The MATH plugin is installed, as well as a private plugin that dumps the exported fonts into ttx files (for version control to see what has changed).

Now both plugins act on the DOCUMENTEXPORTED callback, but the order in which the callback methods are called is different from machine to machine. So sometimes the ttx dump is missing the MATH table even though it is present in the exported font.

I thought a solution would be to add an option to disable the MATHPlugin's export callback and call the MATH table building code from my own plugin myself. So I refactored some of the logic into a module which lives in the MATHPlugin's Resources directory, which is on the Python path and can be imported from my other plugin.

There are no other functional changes in this branch so far, especially the disabling option is not implemented yet. I wanted to hear your opinion first.

### CODE REVIEW

**Comment by jenskutilek** [comment]
I tried to implement the disabling and external calling of the math table builder and it seems to work.

The disable option would need the changes from this branch: https://github.com/jenskutilek/Glyphs-MATH-Plugin/pull/1

**Comment by khaledhosny** [comment]
Looks good to me. I don’t understand the commit message of the second commit, though. It should be fine to have the option commit as well.

**Comment by jenskutilek** [comment]
> I don’t understand the commit message of the second commit, though.

You mean the "force update" thing? It should have disappeared as I squashed the commits. It was just that Glyphs force-updates git repos in its "Repositories" folder and overwrote my changes so I had to fix it up.

I've included the disabling option now.

**Comment by khaledhosny** [comment]
Thanks!

**Comment by florianpircher** [comment]
> You mean the "force update" thing? It should have disappeared as I squashed the commits. It was just that Glyphs force-updates git repos in its "Repositories" folder and overwrote my changes so I had to fix it up.

Glyphs should stash changes in the working copy before updating. Any changes that you have made can be recovered from there.

Otherwise, it’s best to develop plugin code that is outside the *Repositories* directory managed by Glyphs. Either keep the repository directly in the *Plugins* directory or keep the repository somewhere else (e.g., `~/Developer/…`) and symlink it into the *Plugins* directory.

**Comment by jenskutilek** [comment]
> Glyphs should stash changes in the working copy before updating. Any changes that you have made can be recovered from there.

There was a stash, but I had to fix one or two files manually because of conflicts. I think I may have committed some changes before I noticed the other stuff was stashed. Don't remember exactly now ...

> Otherwise, it’s best to develop plugin code that is outside the _Repositories_ directory managed by Glyphs. Either keep the repository directly in the _Plugins_ directory or keep the repository somewhere else (e.g., `~/Developer/…`) and symlink it into the _Plugins_ directory.

Yes, Georg told me as much, and that's how I normally do it. I should have known :)

**Pull request merged**
